#!/usr/bin/env bash

# Color styling.
getColorCode() {
    tput "$@" 2>/dev/null || true
}

COLOR_NORMAL=$(getColorCode sgr0)
COLOR_BLACK=$(getColorCode setaf 0)
COLOR_RED=$(getColorCode setaf 1)
COLOR_GREEN=$(getColorCode setaf 2)
COLOR_YELLOW=$(getColorCode setaf 3)
COLOR_BLUE=$(getColorCode setaf 4)
COLOR_MAGENTA=$(getColorCode setaf 5)
COLOR_CYAN=$(getColorCode setaf 6)
COLOR_WHITE=$(getColorCode setaf 7)

TEXT_BOLD=$(getColorCode bold)

##
# restartPanel
#
    echo
    echo -e "${COLOR_GREEN}""Restarting LxQt Panel.""${COLOR_NORMAL}"

    nohup sh -c 'killall lxqt-panel; sleep 1; lxqt-panel' \
        >> /dev/null 2>&1 &
    RESULT=$?

    echo
    echo -e "${COLOR_GREEN}""Restart LxQt Panel complete."\
        "${COLOR_NORMAL}"
    exit "$RESULT"
