#!/usr/bin/env bash

# Color styling.
getColorCode() {
    tput "$@" 2>/dev/null || true
}

COLOR_NORMAL=$(getColorCode sgr0)
COLOR_BLACK=$(getColorCode setaf 0)
COLOR_RED=$(getColorCode setaf 1)
COLOR_GREEN=$(getColorCode setaf 2)
COLOR_YELLOW=$(getColorCode setaf 3)
COLOR_BLUE=$(getColorCode setaf 4)
COLOR_MAGENTA=$(getColorCode setaf 5)
COLOR_CYAN=$(getColorCode setaf 6)
COLOR_WHITE=$(getColorCode setaf 7)

TEXT_BOLD=$(getColorCode bold)

##
# displayInstalledQmFile
#
    echo
    echo  -e "${COLOR_GREEN}""Displaying source for an install .qm file."\
        "${COLOR_NORMAL}"

    # Ensure there's a locale to use.
    if [[ "$1" == "" ]]; then
        echo
        echo -e "${COLOR_YELLOW}""   try: |"$0""\
            "/usr/share/lxqt/translations/lxqt-panel/stoplight/stoplight_fr.qm|"\
            "${COLOR_NORMAL}"
        echo
        echo -e "${COLOR_GREEN}""Translating one string to all"\
            "languages complete.""${COLOR_NORMAL}"
        exit 1
    fi

    echo
    /usr/lib/qt6/bin/lconvert -i "$1"
    RESULT=$?

    echo
    echo -e "${COLOR_GREEN}""Displaying source for an install"\
        ".qm file complete.""${COLOR_NORMAL}"
    exit "$RESULT"
