#!/usr/bin/env bash

# Color styling.
getColorCode() {
    tput "$@" 2>/dev/null || true
}

COLOR_NORMAL=$(getColorCode sgr0)
COLOR_BLACK=$(getColorCode setaf 0)
COLOR_RED=$(getColorCode setaf 1)
COLOR_GREEN=$(getColorCode setaf 2)
COLOR_YELLOW=$(getColorCode setaf 3)
COLOR_BLUE=$(getColorCode setaf 4)
COLOR_MAGENTA=$(getColorCode setaf 5)
COLOR_CYAN=$(getColorCode setaf 6)
COLOR_WHITE=$(getColorCode setaf 7)

TEXT_BOLD=$(getColorCode bold)

##
# displayLocales
#
    echo
    echo  -e "${COLOR_GREEN}""Displaying available locales.""${COLOR_NORMAL}"

    locale -a
    RESULT=$?

    echo
    echo -e "${COLOR_GREEN}"Available locales displayed.""${COLOR_NORMAL}"
    exit "$RESULT"
